---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testi
  namespace: jes
spec:
  selector:
    matchLabels:
      app: jes
  replicas: 1
  template:
    metadata:
      labels:
        app: jes
    spec:
      shareProcessNamespace: false
      initContainers:
      - name: iolimit
        image: mattirantakomi/iolimit:20230726-6
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: RBPS
          value: "5242880" # 5242880 = 5 MB/s, 10485760 = 10 MB/s
        - name: WBPS
          value: "5242880" # 5242880 = 5 MB/s, 10485760 = 10 MB/s
        - name: RIOPS
          value: "500"
        - name: WIOPS
          value: "500"
        securityContext:
          privileged: true
      containers:
      - name: ubuntu
        image: ubuntu
        command: [ "/bin/sh" , "-c", "tail -f /dev/null" ]
      - name: ubuntu2
        image: ubuntu
        command: [ "/bin/sh" , "-c", "tail -f /dev/null" ]
        securityContext:
          privileged: true
